import Head from 'next/head';

import YearSummary from '../components/YearSummary';



export default function Home({appdata}) {
	const {app} = appdata;
	const yearSummaryItems = app.years.map((y, k) => <YearSummary key={k} year={y} />);

	return (
		<div>
			<Head>
				<title>UPSC Prelims Answer Pattern</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<section className="max-w-5xl mx-auto">
					<div>{yearSummaryItems}</div>
				</section>
			</main>
		</div>
	);
}
