import Head from 'next/head';

import Header from '../Header';



export default function HomePage ({appdata}) {
	const {app} = appdata;

	const elevenRows = app.eleven.map((e, k) => {
		return (
			<tr key={k}>
				<td>{e.year}</td>
				<td>{e.nA}</td>
				<td>{e.nB}</td>
				<td>{e.nC}</td>
				<td>{e.nD}</td>
				<td>{e.nS}</td>
				<td>{e.nM}</td>
			</tr>
		);
	});

	return (
		<div>
			<Head>
				<title>Prelims Pattern</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header page={app.asYear} />

			<section className="max-w-xl mx-auto">
				<div className="py-6">
					<table>
						<thead>
							<tr>
								<td>Year</td>
								<td>A</td>
								<td>B</td>
								<td>C</td>
								<td>D</td>
								<td>Statements</td>
								<td>Matching</td>
							</tr>
						</thead>
						<tbody>{elevenRows}</tbody>
					</table>
				</div>
			</section>
		</div>
	);
}
