import Head from 'next/head';

import Header from '../Header';
import TenYearBarGraph from './TenYearBarGraph';



export default function HomePage ({appdata}) {
	const {app} = appdata;

	const elevenRows = app.eleven.map((e, k) => {
		return (
			<tr key={k}>
				<td>{e.year}</td>
				<td>{e.nA}</td>
				<td>{e.nB}</td>
				<td>{e.nC}</td>
				<td>{e.nD}</td>
				<td>{e.nS}</td>
				<td>{e.nM}</td>
			</tr>
		);
	});

	return (
		<div>
			<Head>
				<title>Prelims Pattern</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header page={app.asYear} />

			<section className="max-w-xl mx-auto">
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nA} title="Number of As" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nB} title="Number of Bs" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nC} title="Number of Cs" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nD} title="Number of Ds" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nS} title="Questions with Statements" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nM} title="Matchings" />
				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nSimple} title="Simple Questions" />
			</section>

			<section className="max-w-xl mx-auto">
				<div className="py-6">
					<table>
						<thead>
							<tr>
								<td>Year</td>
								<td>A</td>
								<td>B</td>
								<td>C</td>
								<td>D</td>
								<td>Statements</td>
								<td>Matching</td>
							</tr>
						</thead>
						<tbody>{elevenRows}</tbody>
					</table>
				</div>
			</section>
		</div>
	);
}
