import Head from 'next/head';

import Header from '../Header';
import AbcdGraph from './AbcdGraph';
import TenYearBarGraph from './TenYearBarGraph';



export default function HomePage ({appdata}) {
	const {app} = appdata;

	const abcdProps = {
		app: app,
		getLabel: y => y.year,
		min: 15,
		max: 40
	};

	return (
		<div>
			<Head>
				<title>Prelims Pattern</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header page={app.asYear} />

			<section className="max-w-5xl bg-slate-100 mx-auto lg:px-4">
				<AbcdGraph app={app} getLabel={y => y.year} getData={(y) => y.nA} title="ABCD over the years" />

				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nSimple} title="Number of Simple Questions" max={70} />
				<AbcdGraph app={app} getLabel={y => y.year} filter={q => q.simple} title="Answer distribution for Simple Questions (%)" max={50} />

				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nS} title="Number of Questions with Statements" max={70} />
				<AbcdGraph app={app} getLabel={y => y.year} filter={q => q.statements} title="Answer distribution for Questions with Statements (%)" max={50} />

				<TenYearBarGraph app={app} getLabel={(y) => y.year} getData={(y) => y.nM} title="Matchings" max={20} />
				<TenYearBarGraph {...abcdProps}  getData={(y) => y.nA} title="Number of As" />
				<TenYearBarGraph {...abcdProps}  getData={(y) => y.nB} title="Number of Bs" />
				<TenYearBarGraph {...abcdProps}  getData={(y) => y.nC} title="Number of Cs" />
				<TenYearBarGraph {...abcdProps}  getData={(y) => y.nD} title="Number of Ds" />

				{[...Array(5)].map((e, k) => {
					const start = (k * 20) + 1;
					const end = start + 19;
					const filter = q => (q.number >= start) && (q.number <= end);
					const title = `Answer distribution for Q${start} to Q${end}`;

					return (
						<div key={k}>
							<AbcdGraph app={app} getLabel={y => y.year} filter={filter} title={title} max={70} />
						</div>
					);
				})}

				<div className="h-20"></div>
			</section>
		</div>
	);
}
